### ISSUE TITLE
20-30 sek in Bubble

### ISSUE THREAD

**Issue by JonasFisch** [m2-retro-mmo/bubble-bobble#196]
- testen was passiert wenn man nochmal eingesperrt wird obwohl man schon in bubble ist! (besondern auf die timer achten)
- lösung, nochmal einsperren blockieren !!!

**Comment by vdrongow** [comment]
Vllt wurde das uncapture auch einfach nicht an die clients übertragen, weil der Server überlastet war? → also erübrigt sich evtl eh wenn alles nochmal performanter ist?
