### ISSUE TITLE
IMPORTANT: Keine neuen Diamanten gespawnt

### ISSUE THREAD

**Issue by JonasFisch** [m2-retro-mmo/bubble-bobble#198]

**Comment by Masa-99** [comment]
make diamond spawning depending on the amount of diamonds on the map

**Comment by JonasFisch** [comment]
- die Botgruppe ruf CoRouteine StopEverthing auf, vllt löst das den Bug aus!

**Comment by JonasFisch** [comment]
check if diamonds that were droped are tracked by the spanwing behavior

**Comment by Masa-99** [comment]
Diamond Manager einbauen, der genauen überblickt hat über Anzahl von Diamonds

**Comment by Masa-99** [comment]
allgemein mehr Diamonds rein

**Comment by Masa-99** [comment]
<img width="319" alt="Bildschirm­foto 2023-02-07 um 18 34 48" src="https://user-images.githubusercontent.com/44638953/217321161-41a234a9-30ce-47ce-b1e0-acbb01985b49.png">
der erste Aufruf zum placen der diamonds stimmt, alle danach sollte es nicht geben

**Comment by Masa-99** [comment]
Konnte gelöst werden durch Eliminierung der Endlosschleife.
Ein letzter komischer Bug ist noch da, am Anfang wird die Methode zweimal aufgerufen und somit insgesamt 100 Diamonds gespawnt.
<img width="1011" alt="Bildschirm­foto 2023-02-07 um 19 10 38" src="https://user-images.githubusercontent.com/44638953/217330030-594318b6-6b11-4b15-83d2-ce6d10733386.png">

**Comment by Masa-99** [comment]
Das Problem hab ich gehackt in dem ich nicht die Hälfte als threshold fürs neue spawning mache, sondern einfach wenn weniger als die generatorData festlegt (50) (also die hälfte von 100)
